### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by sergiodxa** [MiguhRuiz/SpotifyReact#1]
- **Linter**: no configuraste un linter :( en cualquier proyecto y librería es importante hacerlo, y usarlo siempre te ayuda a ser mejor desarrollador.

- **Obtener datos**: cuando usas [next.js](https://github.com/zeit/next.js/) podés definir un método estático llamado `getInitialProps` para obtener los datos (tanto en el frontend como en el servidor) y así hacer el server-render con datos, en vez de eso los estás obteniendo solo en el frontend.

- **Componentes de páginas**: en la carpeta `pages` los componentes básicamente solo sirven para definir el `Provider` y estás creando dentro de `components` otra carpeta `pages` con el verdadero contenido, deberías unir estos archivos y en todo caso separar más la UI de la lógica.

- **Nombre de archivos**: la práctica general al nombrar archivo que exporten componentes de React es que estos tengan el nombre del archivo en PascalCase igual que los componentes que exportan. Un ejemplo de esto es **material-ui** donde el componente `AppBar` lo importas con el path `material-ui/AppBar` esto es porque hay un archivo `AppBar.js` con ese nombre en PascalCase.

- **Cache de datos en el Store**: cuando cargas los datos de un track o album los guardas en el store, pero si luego volves a necesitar esos datos en vez de leerlos desde el store los pedir por AJAX, las API (más las públicas) tienden a tener un límite de peticiones por IP, si no aprovechas la cache que te provee Redux vas a alcanzar el límite de peticiones inutilizando la aplicación durante un tiempo.

- **Guardar en el estado datos innecesarios**: en [track.js:39](https://github.com/MiguhRuiz/SpotifyReact/blob/master/components/pages/track.js#L39) estás guardando el ID que llega como props en el estado, pero jamás cambias ese ID por lo que no es necesario guardarlo ahí.

- **Logs**: mandaste a producción los logs de redux-logger, esto puede darle información sensible sobre tu aplicación a cualquier atacante.

- **Usa `replace`**: en [api.js:10](https://github.com/MiguhRuiz/SpotifyReact/blob/master/lib/api.js#L10) usas un `split` y un `join`, para reemplazar un caracter, mejor usa `replace`y un regex.

- **Usa clases donde sea necesario nada más**: el API está hecho con una clase (que luego instancias al momento de hacer el export), para eso es mejor directamente hacer un objeto plano de JS, no estás obteniendo ninguna ventaja de usar clases (si es que existen en primer lugar) y con un objeto podrías (eventualmente) agrupar bajo una `key` métodos relacionados (como en el curso).

- **Usa nombres de variables/constantes descriptivos**: en [searchBox.js:46](https://github.com/MiguhRuiz/SpotifyReact/blob/master/components/searchBox.js#L46) y en otras partes usas nombres de variables como `e` o `ev`, se que es más cómodo usar una dos letras, pero los editores de código moderno son lo suficientemente buenos autocompletando código como para que no tengas que escribir el nombre de la constante completo y usar nombres como `e` no son para nada descriptivos, en cambio usar `element` o `event` son super descriptivos y dejan en claro desde un primer momento que datos hay almacenado en esa variable/constante.

Hay otras cosas que si configuras el linter vas a notar.

**Comment by MiguhRuiz** [comment]
Aprecio mucho tu feedback y mañana me voy a poner a ello, solo me gustaría comentarte alguna de las anotaciones:

Con respecto a **Componentes de páginas** lo tuve que hacer porque `react-redux` me da un fallo ya que según la librería no se puede hacer `connect` e importar el `<Provider />` en el mismo componente. Es por eso que hice lo de los componentes 😕

Con respecto a **Guardar en el estado datos innecesarios** lo hago porque al ser el componente raíz no puedo obtener el parámetro de la URL, ¿Existe alguna otra manera más eficiente?

Espero tu respuesta @sergiodxa para poder tener claro estos puntos y poder solucionarlos todos de una. ¡Muchas gracias por todo y felices fiestas! 😬

**Comment by sergiodxa** [comment]
Si no podés usar `connect` entonces podés manejar la subscripción al store por vos mismo. En el `componentDidMount` podés hacer `store.subscribe` para subscribirte a los cambios del store (y recuerda desuscribirte en `componentWillUnmount`).

Con el otro punto, me refiero a que en el archivo https://github.com/MiguhRuiz/SpotifyReact/blob/master/components/pages/track.js esto:
```js
    constructor(props) {
        super(props)
        this.state = {
            loading: true,
            id: props.id
        }
    }
```
Ese `props.id` lo estás asignado al `state`, pero nunca lo modificas, por lo que no tiene sentido mandarlos al estado, además que solo lo usas en este método:
```js
    async componentDidMount() {
        await this.props.actions.loadTrack(this.state.id)

        this.setState({
            loading: false
        })
    }
```
Ahí podrías usar `this.props.id` directamente.

**Comment by MiguhRuiz** [comment]
Tras 646e1d8 me encuentro con que si pides dos artistas diferentes en el buscador se mezclan los resultados porque así es como se comporta `.reduce()`. Intenté solucionarlo con un map pero no me salió bien.

También las canciones en el álbum están desordenadas y si las retorno en el reduce por el número de canción para que salgan en orden luego no puedo coger del caché los datos al pedir una Track.

¿Alguna idea para solucionar estos contratiempos? ¡Feliz 2017! 🎉 @sergiodxa

**Comment by sergiodxa** [comment]
Sobre el tema del orden, lo mejor es que mantengas una estructura así:
```js
{
  entities: { 1: {}, 2: {}, 3{} },
  order: [1,3],
}
```
Donde `entities` contiene los datos de cada entidad y `order` mantiene una lista de que entidades mostrar y en que orden, de esta forma cuando vas a mostrar una lista de elementos iteras la lista y usando el ID podés obtener cada entidad.

Esto también te permite tener guardados los datos de entidades que no están siendo mostradas en la UI y luego simplemente cambiando la lista de `order` modificar que entidades mostrar.


Sobre el otro punto, no entiendo bien que ocurre 🤔 . Por lo que ví en el commit no guardas los datos del artista en el store así que no entiendo bien el problema con `reduce`.

**Comment by MiguhRuiz** [comment]
Gracias por la idea del orden, me pongo a ello.

Con respecto a lo otro, me refiero a que si buscas por ejemplo "ACDC" y sin moverte de pantalla vuelves a buscar "The Beatles" se mezclan los resultados(el motivo es que en el reducer se hace un `.reduce()`, por lo que se quedan los dos datos y se presentan ambos mezclados) pero no se como borrar los primeros datos para que no se junten con los otros. @sergiodxa

**Comment by MiguhRuiz** [comment]
Quedaría solucionar lo que te mencioné antes y lo del Store que no tengo mucha idea. Estuve probando pero no me sale. Voy a hacer release y a subirlo. Quedo a la espera de si me puedes proporcionar ayuda 😄 @sergiodxa
